import { createHash } from 'node:crypto'
import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { inferAttachmentSlot } from '../src/buildSolver.ts'
import { consensusBuilds } from '../src/generated/consensusBuilds.ts'
import { consensusSlotMapping, isLayerBSlot } from '../src/slotAuthority.ts'

const SOURCE_URL =
  process.env.BF6_ATTACHMENT_SHEET_URL ??
  'https://docs.google.com/spreadsheets/d/e/2PACX-1vRMZduKhsB9OmLZT6hjwvh8JHvN0-6PXjBccEuhI2WoeO4v_U-zBT2NtzMHeEb9NRETtLS9H_LoJ0M8/pub?output=csv'
const OUTPUT_PATH = resolve('src/generated/attachmentData.ts')

const effectColumns = [
  ['recoilControl', 2],
  ['recoilPrecision', 3],
  ['accuracyOverTime', 4],
  ['adsMovingAccuracy', 5],
  ['adsTimeTier', 6],
  ['drawSpeed', 7],
  ['adsMovementSpeed', 8],
  ['recoilRecovery', 9],
  ['projectileVelocity', 10],
  ['weaponSway', 11],
  ['hipfire', 12],
  ['hidingVisibility', 13],
]

function parseCsv(input) {
  const rows = []
  let row = []
  let value = ''
  let quoted = false

  for (let index = 0; index < input.length; index += 1) {
    const char = input[index]
    const next = input[index + 1]

    if (quoted) {
      if (char === '"' && next === '"') {
        value += '"'
        index += 1
      } else if (char === '"') {
        quoted = false
      } else {
        value += char
      }
      continue
    }

    if (char === '"') {
      quoted = true
    } else if (char === ',') {
      row.push(value)
      value = ''
    } else if (char === '\n') {
      row.push(value)
      rows.push(row)
      row = []
      value = ''
    } else if (char !== '\r') {
      value += char
    }
  }

  if (value || row.length > 0) {
    row.push(value)
    rows.push(row)
  }

  return rows
}

function numberOrUndefined(value) {
  if (value === undefined || value === null || String(value).trim() === '') return undefined
  const parsed = Number(String(value).trim())
  return Number.isFinite(parsed) ? parsed : undefined
}

function normalizeAttachmentId(name) {
  return name.toUpperCase().replace(/[^A-Z0-9]/g, '')
}

function normalizeConsensusAttachmentId(name, slot) {
  return `${normalizeAttachmentId(slot)}_${normalizeAttachmentId(name)}`
}

function readAttachmentRows(rows) {
  return rows
    .map((row) => {
      const name = row[1]?.trim()
      const pointCost = numberOrUndefined(row[16])
      if (!name || name === 'Effect' || pointCost === undefined) return undefined

      const effects = Object.fromEntries(
        effectColumns
          .map(([key, index]) => [key, numberOrUndefined(row[index])])
          .filter(([, value]) => value !== undefined),
      )

      return {
        id: normalizeAttachmentId(name),
        name,
        slot: inferAttachmentSlot(name),
        pointCost,
        totalEffectPoints: numberOrUndefined(row[15]),
        effects,
        layer: 'A',
        source: 'public-csv',
        sourceUrl: SOURCE_URL,
        notes: row[17]?.trim() || undefined,
      }
    })
    .filter(Boolean)
}

function readConsensusAttachmentRows(existingAttachments) {
  const byId = new Map(existingAttachments.map((attachment) => [attachment.id, attachment]))

  for (const build of Object.values(consensusBuilds.builds)) {
    for (const attachment of build.attachments) {
      const slot = consensusSlotMapping[attachment.slotType]
      if (!slot || !isLayerBSlot(slot)) continue

      const id = normalizeConsensusAttachmentId(attachment.name, slot)
      if (byId.has(id)) continue

      byId.set(id, {
        id,
        name: attachment.name,
        slot,
        pointCost: attachment.pointCost,
        layer: 'B',
        source: 'battlefieldmeta.gg',
        sourceUrl: attachment.sourceUrl,
        fetchTimestamp: attachment.fetchTimestamp,
        unlockLevel: attachment.unlockLevel,
      })
    }
  }

  return [...byId.values()]
}

function stableStringify(value) {
  return JSON.stringify(value, null, 2)
}

async function main() {
  const response = await fetch(SOURCE_URL)
  if (!response.ok) {
    throw new Error(`Failed to fetch attachment sheet: ${response.status} ${response.statusText}`)
  }

  const csv = await response.text()
  const rows = parseCsv(csv)
  const csvAttachments = readAttachmentRows(rows)
  const attachments = readConsensusAttachmentRows(csvAttachments)
  const sourceHash = createHash('sha256').update(csv).digest('hex').slice(0, 16)

  const dataset = {
    schemaVersion: 2,
    sourceUrl: SOURCE_URL,
    sourceHash,
    consensusSource: {
      source: consensusBuilds.source,
      fetchedAt: consensusBuilds.fetchedAt,
      schemaVersion: consensusBuilds.schemaVersion,
    },
    attachments,
  }

  const file = `// Generated by scripts/ingestAttachments.mjs. Do not edit by hand.\nexport const generatedAttachmentData = ${stableStringify(dataset)} as const\n`

  await mkdir(dirname(OUTPUT_PATH), { recursive: true })
  await writeFile(OUTPUT_PATH, file, 'utf8')
  console.log(
    `Generated ${attachments.length} attachments: ${csvAttachments.length} public CSV + ${attachments.length - csvAttachments.length} consensus layer B (${sourceHash}).`,
  )
}

main().catch((error) => {
  console.error(error)
  process.exitCode = 1
})
