import { writeFile } from 'node:fs/promises'
import * as cheerio from 'cheerio'

const homeUrl = 'https://www.ea.com/it/games/battlefield/battlefield-6'
const seedPatchUrls = [
  'https://www.ea.com/it/games/battlefield/battlefield-6/news/battlefield-6-game-update-1-3-1-5',
]

const monthByItalianName = new Map([
  ['gennaio', '01'],
  ['febbraio', '02'],
  ['marzo', '03'],
  ['aprile', '04'],
  ['maggio', '05'],
  ['giugno', '06'],
  ['luglio', '07'],
  ['agosto', '08'],
  ['settembre', '09'],
  ['ottobre', '10'],
  ['novembre', '11'],
  ['dicembre', '12'],
])

const highImpactPattern =
  /\b(dann|damage|rinculo|recoil|spread|ttk|time to kill|weapon balance|bilanciamento(?:\s+\w+){0,4}\s+armi|armor damage|attachment cost)\b/i
const redsecImpactPattern = /\b(redsec|battle royale|classificata|ranked|rientrare|rischier|redeploy|respawn|mtn-55|gadget|veicol)/i

async function main() {
  const urls = await discoverPatchUrls()
  const candidates = await Promise.all(urls.map(parsePatchUrl))
  const patches = candidates
    .filter((candidate) => candidate !== undefined)
    .sort((a, b) => compareVersion(b.version, a.version) || b.publishedDate.localeCompare(a.publishedDate))

  const currentPatch = patches[0]
  if (!currentPatch) {
    throw new Error('No Battlefield 6 official patch notes found')
  }

  const output = {
    schemaVersion: 1,
    generatedAt: new Date().toISOString(),
    source: {
      label: 'EA Battlefield 6 Game Updates',
      url: homeUrl,
    },
    currentPatch,
    previousMetaRelevantPatch: {
      version: '1.3.1.0',
      title: {
        it: 'Game Update 1.3.1.0 / Season 3',
        en: 'Game Update 1.3.1.0 / Season 3',
      },
      publishedDate: '2026-05-08',
      sourceUrl: 'https://www.ea.com/en/games/battlefield/battlefield-6/news/season-3-roadmap-everything-you-need-to-know',
      metaImpactLevel: 'high',
      summary: {
        it: 'Update Season 3 con nuovi contenuti e pass dichiarato su armi, gadget e launcher. E la baseline meta che ha richiesto refresh completo.',
        en: 'Season 3 update with new content and a declared pass across weapons, gadgets, and launchers. This is the meta baseline that required a full refresh.',
      },
    },
  }

  await writeFile(
    'src/generated/patchStatus.ts',
    `// Generated by scripts/ingestPatchNotes.mjs. Do not edit by hand.\nexport const generatedPatchStatus = ${JSON.stringify(
      output,
      null,
      2,
    )} as const\n`,
  )
}

async function discoverPatchUrls() {
  const urls = new Set(seedPatchUrls)

  try {
    const html = await fetchText(homeUrl)
    const matches = html.matchAll(/https:\/\/www\.ea\.com\/it\/games\/battlefield\/battlefield-6\/news\/battlefield-6-[^"']*update[^"']*?1-\d-\d-\d/gi)
    for (const match of matches) urls.add(match[0])

    const relativeMatches = html.matchAll(/href="(\/it\/games\/battlefield\/battlefield-6\/news\/battlefield-6-[^"]*update[^"]*?1-\d-\d-\d)"/gi)
    for (const match of relativeMatches) urls.add(`https://www.ea.com${match[1]}`)
  } catch (error) {
    console.warn(`[patch] unable to discover update links from EA home: ${error.message}`)
  }

  return [...urls]
}

async function parsePatchUrl(url) {
  try {
    const html = await fetchText(url)
    const $ = cheerio.load(html)
    const bodyText = normalizeText($('body').text())
    const titleText = normalizeText($('h1').first().text())
    const version = titleText.match(/(\d+\.\d+\.\d+\.\d+)/)?.[1] ?? url.match(/(\d-\d-\d-\d)/)?.[1]?.replaceAll('-', '.')

    if (!version) return undefined

    const publishedDate = parseItalianDate(bodyText) ?? '2026-05-22'
    const effectiveAt = parseEffectiveDate(bodyText, publishedDate)
    const sections = extractSections($)
    const weaponBalanceChanged = sections.some((section) => section.items.some((item) => highImpactPattern.test(item.it)))
    const redsecFlowChanged = sections.some((section) => section.items.some((item) => redsecImpactPattern.test(item.it)))
    const metaImpactLevel = weaponBalanceChanged ? 'high' : redsecFlowChanged ? 'medium' : 'low'

    return {
      version,
      title: {
        it: titleText || `Battlefield 6 - Note sull'aggiornamento ${version}`,
        en: `Battlefield 6 Game Update ${version}`,
      },
      publishedDate,
      effectiveAt,
      sourceUrl: url,
      metaImpactLevel,
      weaponBalanceChanged,
      redsecFlowChanged,
      rankingDecision: weaponBalanceChanged
        ? {
            it: 'Ricalcolo ranking richiesto: la patch contiene segnali di bilanciamento armi o attachment.',
            en: 'Ranking recalculation required: the patch contains weapon or attachment balance signals.',
          }
        : {
            it: 'Ranking armi invariato: nelle note ufficiali non ci sono modifiche a danni, recoil, spread, TTK o costi attachment.',
            en: 'Weapon ranking unchanged: the official notes do not include damage, recoil, spread, TTK, or attachment-cost changes.',
          },
      plannerDecision: redsecFlowChanged
        ? {
            it: 'Planner da monitorare: REDSEC riceve fix su ranked, rientro/rischieramento o gadget che possono cambiare il flow dei fight.',
            en: 'Planner watch: REDSEC receives ranked, respawn/redeploy, or gadget fixes that can change fight flow.',
          }
        : {
            it: 'Planner invariato: nessun cambio rilevante a regole REDSEC, gadget o veicoli.',
            en: 'Planner unchanged: no relevant REDSEC rules, gadget, or vehicle changes.',
          },
      summary: summarizePatch(version, weaponBalanceChanged, redsecFlowChanged),
      sections,
    }
  } catch (error) {
    console.warn(`[patch] unable to parse ${url}: ${error.message}`)
    return undefined
  }
}

async function fetchText(url) {
  const response = await fetch(url, {
    headers: {
      'user-agent': 'BF6Bible patch status bot (fan site; reads public EA patch notes)',
    },
  })
  if (!response.ok) throw new Error(`HTTP ${response.status}`)
  return response.text()
}

function normalizeText(value) {
  return value.replace(/\s+/g, ' ').trim()
}

function parseItalianDate(text) {
  const match = text.match(/(\d{1,2})\s+(gennaio|febbraio|marzo|aprile|maggio|giugno|luglio|agosto|settembre|ottobre|novembre|dicembre)\s+(20\d{2})/i)
  if (!match) return undefined
  const [, day, monthName, year] = match
  return `${year}-${monthByItalianName.get(monthName.toLowerCase())}-${day.padStart(2, '0')}`
}

function parseEffectiveDate(text, publishedDate) {
  const match = text.match(/(?:disponibile|arriva|pubblicat\w*)\s+(?:il\s+)?(\d{1,2})\s+(gennaio|febbraio|marzo|aprile|maggio|giugno|luglio|agosto|settembre|ottobre|novembre|dicembre)(?:\s+(?:alle|a)\s+(\d{1,2}):(\d{2})\s+CEST)?/i)
  if (!match) return `${publishedDate}T00:00:00.000Z`
  const [, day, monthName, hour = '00', minute = '00'] = match
  const year = publishedDate.slice(0, 4)
  const utcHour = Math.max(0, Number(hour) - 2)
  return `${year}-${monthByItalianName.get(monthName.toLowerCase())}-${day.padStart(2, '0')}T${String(utcHour).padStart(2, '0')}:${minute}:00.000Z`
}

function extractSections($) {
  const wanted = new Map([
    ['GADGET', { id: 'gadgets', label: { it: 'Gadget', en: 'Gadgets' } }],
    ['VEICOLI', { id: 'vehicles', label: { it: 'Veicoli', en: 'Vehicles' } }],
    ['MAPPE E MODALITÀ', { id: 'maps-modes', label: { it: 'Mappe e modalità', en: 'Maps and modes' } }],
    ['REDSEC', { id: 'redsec', label: { it: 'REDSEC', en: 'REDSEC' } }],
    ['ARMI', { id: 'weapons', label: { it: 'Armi', en: 'Weapons' } }],
    ['PORTAL', { id: 'portal', label: { it: 'Portal', en: 'Portal' } }],
  ])

  const sections = []
  $('h2, h3').each((_, heading) => {
    const headingText = normalizeText($(heading).text()).toUpperCase()
    const match = [...wanted.entries()].find(([key]) => headingText.includes(key))
    if (!match) return

    const [, info] = match
    const items = []
    let cursor = $(heading).next()
    while (cursor.length && !['h2', 'h3'].includes(cursor[0].tagName?.toLowerCase())) {
      cursor.find('li').each((__, item) => {
        const text = normalizeText($(item).text())
        if (text) items.push(toLocalizedPatchItem(text))
      })
      cursor = cursor.next()
    }

    if (items.length > 0 && !sections.some((section) => section.id === info.id)) {
      sections.push({ ...info, impactLevel: sectionImpact(items), items })
    }
  })

  const normalizedSections = splitWeaponItems(sections)

  return normalizedSections.length > 0
    ? normalizedSections
    : [
        {
          id: 'summary',
          label: { it: 'Sintesi', en: 'Summary' },
          impactLevel: 'low',
          items: [
            {
              it: 'Patch ufficiale letta correttamente, ma il parser non ha trovato sezioni strutturate.',
              en: 'Official patch read correctly, but the parser did not find structured sections.',
              metaSignal: 'low',
            },
          ],
        },
      ]
}

function splitWeaponItems(sections) {
  const weaponItems = []
  const cleanedSections = sections
    .map((section) => {
      const items = section.items.filter((item) => {
        const isWeaponItem = /\b(arma|armi|fucile|pistola|smg|lmg|dmr|sniper|cecchino|l115)\b/i.test(item.it)
        if (isWeaponItem && section.id !== 'weapons') {
          weaponItems.push(item)
          return false
        }
        return true
      })

      return items.length > 0 ? { ...section, items, impactLevel: sectionImpact(items) } : undefined
    })
    .filter(Boolean)

  if (weaponItems.length > 0 && !cleanedSections.some((section) => section.id === 'weapons')) {
    cleanedSections.push({
      id: 'weapons',
      label: { it: 'Armi', en: 'Weapons' },
      impactLevel: sectionImpact(weaponItems),
      items: weaponItems,
    })
  }

  return cleanedSections
}

function toLocalizedPatchItem(text) {
  return {
    it: text,
    en: translateKnownLine(text),
    metaSignal: highImpactPattern.test(text) ? 'high' : redsecImpactPattern.test(text) ? 'medium' : 'low',
  }
}

function translateKnownLine(text) {
  if (text.includes('MTN-55')) {
    return 'Improved MTN-55 proximity detector tracking so enemy soldiers are revealed more reliably in some scenarios.'
  }
  if (text.includes('L115')) {
    return 'The L115 sniper rifle model now remains visible after reviving the user who is carrying it.'
  }
  if (text.includes('Battle Royale Classificata') || text.includes('Classificata')) {
    return 'Improved Ranked Battle Royale messaging, progression visibility, scoring display, or lobby customization.'
  }
  if (text.includes('personalizzazione della grafica')) {
    return 'Players can now select graphic customization while in the lobby.'
  }
  if (text.includes('rientrare') || text.includes('rischierarsi')) {
    return 'Fixed issues that could prevent players from respawning, redeploying, or deploying on vehicles.'
  }
  return text
}

function sectionImpact(items) {
  if (items.some((item) => item.metaSignal === 'high')) return 'high'
  if (items.some((item) => item.metaSignal === 'medium')) return 'medium'
  return 'low'
}

function summarizePatch(version, weaponBalanceChanged, redsecFlowChanged) {
  if (weaponBalanceChanged) {
    return {
      it: `La patch ${version} contiene segnali di balance armi: BF6Bible deve ricalcolare ranking e Planner.`,
      en: `Patch ${version} contains weapon-balance signals: BF6Bible should recalculate rankings and Planner picks.`,
    }
  }
  if (redsecFlowChanged) {
    return {
      it: `La patch ${version} non cambia il weapon meta, ma tocca il flow REDSEC tramite fix a ranked, rientro/rischieramento, gadget o veicoli.`,
      en: `Patch ${version} does not change weapon meta, but it touches REDSEC flow through ranked, respawn/redeploy, gadget, or vehicle fixes.`,
    }
  }
  return {
    it: `La patch ${version} e una patch di stabilita e UI: ranking e Planner restano invariati.`,
    en: `Patch ${version} is a stability and UI patch: ranking and Planner remain unchanged.`,
  }
}

function compareVersion(a, b) {
  const left = a.split('.').map(Number)
  const right = b.split('.').map(Number)
  for (let index = 0; index < Math.max(left.length, right.length); index += 1) {
    const diff = (left[index] ?? 0) - (right[index] ?? 0)
    if (diff !== 0) return diff
  }
  return 0
}

main().catch((error) => {
  console.error(error)
  process.exitCode = 1
})
